apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: spc35771/examples-nginx:latest
        name: guestbook-ui
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: coredns
---
apiVersion: v1
kind: LimitRange
metadata:
  annotations:
  name: project-compute-resource-limitsas
spec:
  limits:
  - default:
      memory: 200Mi
    defaultRequest:
      memory: 200Mi
    max:
      memory: 3000Mi
    min:
      memory: 25Mi
    type: Container
  - max:
      storage: 2500Mi
    type: openshift.io/Image
  - max:
      openshift.io/image-tags: "100"
      openshift.io/images: "100"
    type: openshift.io/ImageStream
---
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: 2020-10-14T09:51:04Z
  name: project-pod-limits
  namespace: mohammady
spec:
  hard:
    pods: "10"
  scopes:
  - NotTerminating
status:
  hard:
    pods: "10"
  used:
    pods: "0"
